### ISSUE TITLE
Is the code still working?

### ISSUE THREAD

**Issue by philipperemy** [0x13a/bitcoin-arbitrage#3]
Haven't tried it yet

**Comment by 0x13a** [comment]
yes, but you need to good amount of money to make profit out of arbitrage, since margins are low.

**Comment by philipperemy** [comment]
@0x13a what do you mean? You meant a lot of trading volume would lower the trading fees?

**Comment by sirvon** [comment]
@philipperemy He's saying, the profit margin that you will realize from this trading software by buying and selling  the different prices btw the 2 exchanges is low. So you will need a large amount of capital to realize real money worth the time and effort. But @0x13a, how much starting capital you think your script needs to be a winner?
